---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - namespace.yaml
helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.17.5
    releaseName: rook-ceph
    valuesFile: values.yaml
    namespace: rook-ceph
    includeCRDs: true