---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    version: 4.0.1
    releaseName: glance
    valuesFile: values.yaml

configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=./resources/glance.yaml

generatorOptions:
  disableNameSuffixHash: true
